In [41]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [42]:
def evaluate_model(name, y_test, y_pred):
    from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
    print(f"--- {name} ---")
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, zero_division=0))
    print("Recall:", recall_score(y_test, y_pred, zero_division=0))
    print("F1-Score:", f1_score(y_test, y_pred, zero_division=0))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [43]:
data=pd.read_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Scaling dataset\Scaling_data.xlsx')

In [44]:
data.columns

Index(['Claim_Amount', 'Patient_Age', 'Patient_Gender', 'Patient_State',
       'Provider_State', 'Number_of_Procedures', 'Admission_Type',
       'Length_of_Stay_Days', 'Service_Type', 'Deductible_Amount',
       'CoPay_Amount', 'Number_of_Previous_Claims_Patient',
       'Number_of_Previous_Claims_Provider', 'Provider_Patient_Distance_Miles',
       'Claim_Submitted_Late', 'Is_Fraudulent', 'Provider_Type_Hospital',
       'Provider_Type_Laboratory', 'Provider_Type_Pharmacy',
       'Provider_Type_Specialist Office', 'Provider_Type_Urgent Care',
       'Provider_Specialty_Dermatology', 'Provider_Specialty_General Practice',
       'Provider_Specialty_Neurology', 'Provider_Specialty_Oncology',
       'Provider_Specialty_Orthopedics', 'Provider_Specialty_Pediatrics',
       'Provider_Specialty_Physical Therapy', 'Provider_Specialty_Psychiatry',
       'Provider_Specialty_Radiology', 'Discharge_Type_Deceased',
       'Discharge_Type_Home', 'Discharge_Type_Rehab/Skilled Nursing',
       'Discharge_Type_Transfer to another facility', 'Claim_Year',
       'Claim_Month', 'Claim_Delay_Days'],
      dtype='object')

In [45]:
# train test split
from sklearn.model_selection import train_test_split
X = data.drop('Is_Fraudulent', axis=1)
y = data['Is_Fraudulent']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
X

,Claim_Amount,Patient_Age,Patient_Gender,Patient_State,Provider_State,Number_of_Procedures,Admission_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,-1.121339,-0.650370,0,19,18,-1.217663,0,0,2,0.645337,...,0,0,0,0,0,1,0,-0.796174,-0.086455,0.036400
1,0.913860,-0.194101,2,2,0,-1.217663,0,0,4,0.768881,...,0,0,0,1,0,0,0,1.702260,-1.550441,-1.635309
2,0.365625,1.707018,0,4,12,-1.564551,4,0,5,-0.045775,...,0,0,0,1,0,0,0,0.453043,-0.379252,-0.115574
3,-0.963953,0.148100,2,9,16,-0.523887,3,0,5,-1.330551,...,0,0,0,1,0,0,0,-0.796174,1.377530,-1.521329
4,1.207168,-0.802460,0,4,15,-0.176999,1,0,1,0.373430,...,0,0,0,1,0,0,0,1.077652,-0.964847,-0.343534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20095,-0.089761,-1.372796,1,4,6,1.557441,0,0,1,1.006428,...,0,0,0,0,0,1,0,1.077652,-0.964847,-1.103402
20096,-0.029113,0.566346,2,8,13,1.557441,3,0,2,0.606468,...,0,0,0,0,0,0,0,1.077652,1.084733,-0.115574
20097,0.108135,-1.144661,2,3,2,1.210553,1,0,4,-1.724782,...,0,0,0,0,1,0,0,-0.171565,-0.672050,-0.343534
20098,-1.089525,-0.156079,2,6,10,-0.176999,2,0,1,0.455423,...,0,1,0,0,0,0,1,1.077652,1.084733,-1.407349
20099,-1.545551,0.452279,0,2,5,-0.176999,2,0,3,1.155949,...,0,0,0,0,1,0,0,1.077652,0.791936,0.454327

In [47]:
y

0        0
1        1
2        0
3        1
4        0
        ..
20095    1
20096    0
20097    1
20098    0
20099    0
Name: Is_Fraudulent, Length: 20100, dtype: int64

In [48]:
# Logistic Classification
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [49]:
#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8144278606965174
Precision: 0.7309027777777778
Recall: 0.4160079051383399
F1-Score: 0.5302267002518891
Confusion Matrix:
 [[2853  155]
 [ 591  421]]

In [50]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)
y_pred = dt_pred

evaluate_model(
    "Decision Tree",
    y_test,
    dt_pred)
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

--- Decision Tree ---
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.86      0.86      3008
           1       0.58      0.60      0.59      1012

    accuracy                           0.79      4020
   macro avg       0.72      0.73      0.73      4020
weighted avg       0.79      0.79      0.79      4020

Accuracy: 0.791542288557214
Precision: 0.5843023255813954
Recall: 0.5958498023715415
F1-Score: 0.5900195694716243
Confusion Matrix:
 [[2579  429]
 [ 409  603]]
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.86      0.86      3008
           1       0.58      0.60      0.59      1012

    accuracy                           0.79      4020
   macro avg       0.72      0.73      0.73      4020
weighted avg       0.79      0.79      0.79      4020

Accuracy: 0.791542288557214
Precision: 0.5843023255813954
Recall: 0.5958498023715415
F1-Score: 0.5900195694716243
Confusion Matrix:
 [[2579  429]
 [ 409  603]]

In [51]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
y_pred = rf_pred

evaluate_model(
    "Random Forest",
    y_test,
    rf_pred
)

--- Random Forest ---
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.99      0.91      3008
           1       0.93      0.44      0.60      1012

    accuracy                           0.85      4020
   macro avg       0.89      0.71      0.75      4020
weighted avg       0.86      0.85      0.83      4020

Accuracy: 0.8509950248756218
Precision: 0.9311064718162839
Recall: 0.4407114624505929
F1-Score: 0.5982562038900067
Confusion Matrix:
 [[2975   33]
 [ 566  446]]

In [52]:
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.99      0.91      3008
           1       0.93      0.44      0.60      1012

    accuracy                           0.85      4020
   macro avg       0.89      0.71      0.75      4020
weighted avg       0.86      0.85      0.83      4020

Accuracy: 0.8509950248756218
Precision: 0.9311064718162839
Recall: 0.4407114624505929
F1-Score: 0.5982562038900067
Confusion Matrix:
 [[2975   33]
 [ 566  446]]

In [53]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    random_state=42
)

gb_model.fit(X_train, y_train)

gb_pred = gb_model.predict(X_test)
y_pred = gb_pred

evaluate_model(
    "Gradient Boosting",
    y_test,
    gb_pred
)

--- Gradient Boosting ---
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      3008
           1       0.86      0.48      0.61      1012

    accuracy                           0.85      4020
   macro avg       0.85      0.73      0.76      4020
weighted avg       0.85      0.85      0.83      4020

Accuracy: 0.8485074626865672
Precision: 0.856637168141593
Recall: 0.4782608695652174
F1-Score: 0.6138237159162968
Confusion Matrix:
 [[2927   81]
 [ 528  484]]

In [54]:
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      3008
           1       0.86      0.48      0.61      1012

    accuracy                           0.85      4020
   macro avg       0.85      0.73      0.76      4020
weighted avg       0.85      0.85      0.83      4020

Accuracy: 0.8485074626865672
Precision: 0.856637168141593
Recall: 0.4782608695652174
F1-Score: 0.6138237159162968
Confusion Matrix:
 [[2927   81]
 [ 528  484]]

In [55]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)
y_pred = xgb_pred

evaluate_model(
    "XGBoost",
    y_test,
    xgb_pred
)

--- XGBoost ---
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.93      0.90      3008
           1       0.74      0.57      0.65      1012

    accuracy                           0.84      4020
   macro avg       0.81      0.75      0.77      4020
weighted avg       0.84      0.84      0.84      4020

Accuracy: 0.8425373134328358
Precision: 0.7445161290322581
Recall: 0.5701581027667985
F1-Score: 0.6457750419697817
Confusion Matrix:
 [[2810  198]
 [ 435  577]]

In [56]:
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.93      0.90      3008
           1       0.74      0.57      0.65      1012

    accuracy                           0.84      4020
   macro avg       0.81      0.75      0.77      4020
weighted avg       0.84      0.84      0.84      4020

Accuracy: 0.8425373134328358
Precision: 0.7445161290322581
Recall: 0.5701581027667985
F1-Score: 0.6457750419697817
Confusion Matrix:
 [[2810  198]
 [ 435  577]]

In [57]:
from sklearn.svm import SVC

svm_model = SVC()

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

evaluate_model(
    "SVM",
    y_test,
    svm_pred
)

--- SVM ---
Classification Report:
               precision    recall  f1-score   support

           0       0.79      1.00      0.88      3008
           1       0.93      0.21      0.34      1012

    accuracy                           0.80      4020
   macro avg       0.86      0.60      0.61      4020
weighted avg       0.82      0.80      0.74      4020

Accuracy: 0.7965174129353234
Precision: 0.9330357142857143
Recall: 0.20652173913043478
F1-Score: 0.33818770226537215
Confusion Matrix:
 [[2993   15]
 [ 803  209]]

In [58]:
y_pred = svm_pred
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.79      1.00      0.88      3008
           1       0.93      0.21      0.34      1012

    accuracy                           0.80      4020
   macro avg       0.86      0.60      0.61      4020
weighted avg       0.82      0.80      0.74      4020

Accuracy: 0.7965174129353234
Precision: 0.9330357142857143
Recall: 0.20652173913043478
F1-Score: 0.33818770226537215
Confusion Matrix:
 [[2993   15]
 [ 803  209]]

In [59]:
models = {
    "Decision Tree": dt_pred,
    "Random Forest": rf_pred,
    "Gradient Boosting": gb_pred,
    "XGBoost": xgb_pred,
    "SVM": svm_pred
}

results = []

for model_name, pred in models.items():

    results.append({
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred),
        "Recall": recall_score(y_test, pred),
        "F1 Score": f1_score(y_test, pred)
    })

results_df = pd.DataFrame(results)

results_df

               Model  Accuracy  Precision    Recall  F1 Score
0      Decision Tree  0.791542   0.584302  0.595850  0.590020
1      Random Forest  0.850995   0.931106  0.440711  0.598256
2  Gradient Boosting  0.848507   0.856637  0.478261  0.613824
3            XGBoost  0.842537   0.744516  0.570158  0.645775
4                SVM  0.796517   0.933036  0.206522  0.338188

In [60]:
import os
import joblib
artifacts_dir = r'D:\1.Tekworks\Project\Tekwork-Project\backend\6.Artifacts'
os.makedirs(artifacts_dir, exist_ok=True)
# Save trained models
joblib.dump(dt_model, os.path.join(artifacts_dir, 'decision_tree.pkl'))
joblib.dump(rf_model, os.path.join(artifacts_dir, 'random_forest.pkl'))
joblib.dump(gb_model, os.path.join(artifacts_dir, 'gradient_boosting.pkl'))
joblib.dump(xgb_model, os.path.join(artifacts_dir, 'xgboost.pkl'))
joblib.dump(svm_model, os.path.join(artifacts_dir, 'svm.pkl'))
joblib.dump(model, os.path.join(artifacts_dir, 'logistic_regression.pkl'))
print('Saved models to', artifacts_dir)

Saved models to D:\1.Tekworks\Project\Tekwork-Project\backend\6.Artifacts